version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven
  build:
    commands:
      - echo Building jar...
      - mvn clean package -DskipTests
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo Building Docker image...
      - docker build -t basiccalc-ecr .
      - docker tag basiccalc-ecr:latest 838736784378.dkr.ecr.ap-south-1.amazonaws.com/basiccalc-ecr:latest
      - docker push 838736784378.dkr.ecr.ap-south-1.amazonaws.com/basiccalc-ecr:latest

artifacts:
  files: []
