version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven
      - echo Installing Docker...
      - yum install -y docker
      - nohup dockerd &>/var/log/docker.log &
      - timeout 15 sh -c "until docker info; do sleep 1; done"
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 838736784378.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building JAR...
      - mvn clean package -DskipTests
      - echo Building Docker image...
      - docker build -t basiccalc-ecr .
      - docker tag basiccalc-ecr:latest 838736784378.dkr.ecr.ap-south-1.amazonaws.com/basiccalc-ecr:latest
      - echo Pushing Docker image to ECR...
      - docker push 838736784378.dkr.ecr.ap-south-1.amazonaws.com/basiccalc-ecr:latest
      - echo Build complete.

artifacts:
  files: []
