version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven..."
      - yum install -y maven
  build:
    commands:
      - echo "Running mvn clean package..."
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo "Preparing deploy.zip for EB..."
      - mkdir -p deploy
      - cp target/*.war deploy/ROOT.war
      - zip -r deploy.zip deploy/

artifacts:
  files:
    - deploy.zip
